name: Coverity
on:
  schedule:
    # Run on Mondays
    - cron: '0 5 * * MON'
jobs:
  Coverity:
    needs: Tests
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install llvm libclang-dev python3 python3-setuptools python3-wheel
    - uses: vapier/coverity-scan-action@v0
      with:
        project: yugr%2FFlakyIterators
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        email: ${{ secrets.EMAIL }}
